### ISSUE TITLE
Getting tabular data from latitude-longitude?

### ISSUE THREAD

**Issue by IanQS** [gantian127/soilgrids#5]
Is there a capability to just grab the various points of data from the latitude and longitude? TL;DR I'm wondering if it's possible to construct a CSV dataset from just the latitude and longitude data.

Any help would be appreciated! Thank you!

**Comment by gantian127** [comment]
The original service from SoilGrids system is to get grid data (not points) https://www.isric.org/web-coverage-services-wcs. 
So the current implementation of this package only supports to download grid datasets. If you want to grab various points of data from lat and lon, you probably can first use this package to download the grid data and then use other tools (e.g., rasterio or rioxarray)to load grid data and extract point data from the grid. Here is an example: https://gis.stackexchange.com/questions/358036/extracting-data-from-a-raster
