### ISSUE TITLE
Add  WRB 

### ISSUE THREAD

**Issue by sow-ibrahima** [gantian127/soilgrids#6]
is it possible to add the World Reference Base classification?

![image](https://user-images.githubusercontent.com/59258839/232478593-1f1d5e0f-d158-41ce-a6b2-4c97b3080afa.png)

**Comment by gantian127** [comment]
@sow-ibrahima Thanks for your comment. I will work on this and make it available in a new release. I will let you know after it is ready. Thank you!

**Comment by gantian127** [comment]
@sow-ibrahima A new release v0.1.4 is available which supports wrb map service. I will close this issue and please create a new issue if you find any issues. Thank you!

**Comment by ibrahimasow** [comment]
Thanks Gaitan. 
Will do.
